version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
executors:
  with-chrome:
    docker:
      - image: "cypress/browsers:node16.16.0-chrome107-ff107-edge"
workflows:
  build:
    jobs:
      - cypress/run:
          - run: npm run cy:run
          - run: npm run report
          executor: with-chrome
          browser: chrome
          post-steps:
            - store_artifacts:
                path: mochawesome-report
