version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: "npx cypress run --e2e --browser chrome --headless"
